apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: clima_laboral_app_cloud_architect
  description: Aplicación web completa para gestión de encuestas de clima laboral con IA
  annotations:
    github.com/project-slug: crlsquilumba/clima_laboral_app_cloud_architect
spec:
  type: library
  lifecycle: experimental
  owner: user:default/guest
